{version: 2}
services:
  ttAnode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode1
    hostname: ttAnode1
    tty: 'true'
    volumes: ['/home/centos/network/node1/node1_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=5df2d3f396b27ca87823657c0d9324291b6fd29f@ttAnode5:26656,d943e46b6483f905a4c8ccc5f5e096a614885055@ttAnode3:26656,a5f396d90bd4604048c21ae1980405fdc57d55f1@ttAnode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode1]
  ttAnode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode2
    hostname: ttAnode2
    tty: 'true'
    volumes: ['/home/centos/network/node1/node2_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=74e46dcbaa0ee773572b66954eccaa1f49f9aedc@ttAnode1:26656,e6bd120681b109070dd08cce10bf5a75c8758ebb@ttAnode4:26656,556d7f6a05f3ca33fcbe1e7d378b1cbad5492e21@ttAnode6:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode2]
  ttAnode3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode3
    hostname: ttAnode3
    tty: 'true'
    volumes: ['/home/centos/network/node1/node3_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=74e46dcbaa0ee773572b66954eccaa1f49f9aedc@ttAnode1:26656,a4262020cbacba92dc077a48d211ed1c6963f03a@ttAnode7:26656,e6bd120681b109070dd08cce10bf5a75c8758ebb@ttAnode4:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode3]
  ttAnode4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode4
    hostname: ttAnode4
    tty: 'true'
    volumes: ['/home/centos/network/node1/node4_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=d943e46b6483f905a4c8ccc5f5e096a614885055@ttAnode3:26656,a5f396d90bd4604048c21ae1980405fdc57d55f1@ttAnode2:26656,87b1e9c9cfc87af9b8393081211af134b646cb77@ttAnode8:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode4]
  ttAnode5:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode5
    hostname: ttAnode5
    tty: 'true'
    volumes: ['/home/centos/network/node1/node5_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=74e46dcbaa0ee773572b66954eccaa1f49f9aedc@ttAnode1:26656,a4262020cbacba92dc077a48d211ed1c6963f03a@ttAnode7:26656,556d7f6a05f3ca33fcbe1e7d378b1cbad5492e21@ttAnode6:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode5]
  ttAnode6:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode6
    hostname: ttAnode6
    tty: 'true'
    volumes: ['/home/centos/network/node1/node6_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=5df2d3f396b27ca87823657c0d9324291b6fd29f@ttAnode5:26656,87b1e9c9cfc87af9b8393081211af134b646cb77@ttAnode8:26656,a5f396d90bd4604048c21ae1980405fdc57d55f1@ttAnode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode6]
  ttAnode7:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode7
    hostname: ttAnode7
    tty: 'true'
    volumes: ['/home/centos/network/node1/node7_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=5df2d3f396b27ca87823657c0d9324291b6fd29f@ttAnode5:26656,d943e46b6483f905a4c8ccc5f5e096a614885055@ttAnode3:26656,87b1e9c9cfc87af9b8393081211af134b646cb77@ttAnode8:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode7]
  ttAnode8:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode8
    hostname: ttAnode8
    tty: 'true'
    volumes: ['/home/centos/network/node1/node8_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=e6bd120681b109070dd08cce10bf5a75c8758ebb@ttAnode4:26656,556d7f6a05f3ca33fcbe1e7d378b1cbad5492e21@ttAnode6:26656,a4262020cbacba92dc077a48d211ed1c6963f03a@ttAnode7:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore ']
    networks:
      tendermintnet1:
        aliases: [ttAnode8]
