version: 2
services:
  ttAnode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode1
    hostname: ttAnode1
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node1_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=221e93e5f65a21cea98f01ee640620dd09480963@ttAnode32:26656,a8819b91807edf54dced0448cc4697d4dccb9e84@ttAnode2:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode1
  ttAnode10:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode10
    hostname: ttAnode10
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node10_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=ac947b8efa8b3feb9ac79ef4edd3975df06450a9@ttAnode9:26656,85893b955fc771d60da3041a4307b7e9d446c358@ttAnode11:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode10
  ttAnode11:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode11
    hostname: ttAnode11
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node11_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=bc85bfe8ed27c77143d2c62bace3762b3bc0f1a2@ttAnode10:26656,6225d97fae01025553e40edd701869fd7d6ac6fd@ttAnode12:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode11
  ttAnode12:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode12
    hostname: ttAnode12
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node12_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=85893b955fc771d60da3041a4307b7e9d446c358@ttAnode11:26656,82baa5fe300406489136dc966416b597de7bf345@ttAnode13:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode12
  ttAnode13:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode13
    hostname: ttAnode13
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node13_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=6225d97fae01025553e40edd701869fd7d6ac6fd@ttAnode12:26656,f3efd46cfce07e1f813163889463e8e5c3ffbff0@ttAnode14:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode13
  ttAnode14:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode14
    hostname: ttAnode14
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node14_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=82baa5fe300406489136dc966416b597de7bf345@ttAnode13:26656,5439fb8ab846542d4f8afa110d5d7be9a1b2e6ca@ttAnode15:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode14
  ttAnode15:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode15
    hostname: ttAnode15
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node15_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=f3efd46cfce07e1f813163889463e8e5c3ffbff0@ttAnode14:26656,9c795d0329512fe1522893af835b2641ce969ac0@ttAnode16:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode15
  ttAnode16:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode16
    hostname: ttAnode16
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node16_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=5439fb8ab846542d4f8afa110d5d7be9a1b2e6ca@ttAnode15:26656,9b1ee9db2be25ceb5af70ca06dc76f7ce635a99a@ttAnode17:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode16
  ttAnode17:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode17
    hostname: ttAnode17
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node17_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=9c795d0329512fe1522893af835b2641ce969ac0@ttAnode16:26656,735d3eb34d0f191bc6b5406580f8ac054b7ec9dd@ttAnode18:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode17
  ttAnode18:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode18
    hostname: ttAnode18
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node18_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=9b1ee9db2be25ceb5af70ca06dc76f7ce635a99a@ttAnode17:26656,edb27f1a365a664b838d532b73450db16fcf32f9@ttAnode19:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode18
  ttAnode19:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode19
    hostname: ttAnode19
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node19_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=735d3eb34d0f191bc6b5406580f8ac054b7ec9dd@ttAnode18:26656,e75b956c2fe38e696fe0080e37fa5b4e96095842@ttAnode20:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode19
  ttAnode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode2
    hostname: ttAnode2
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node2_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=1feff0541e8fa3d305b3207de8d3af7f514793b4@ttAnode1:26656,c4e06231035176586f934f07fa5c773fb512dc07@ttAnode3:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode2
  ttAnode20:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode20
    hostname: ttAnode20
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node20_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=edb27f1a365a664b838d532b73450db16fcf32f9@ttAnode19:26656,7776e73bd6104c7022fe2ac744d07ed2a3801989@ttAnode21:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode20
  ttAnode21:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode21
    hostname: ttAnode21
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node21_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=e75b956c2fe38e696fe0080e37fa5b4e96095842@ttAnode20:26656,8aae601028a4459c609a5d2352ca1cecccc2471a@ttAnode22:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode21
  ttAnode22:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode22
    hostname: ttAnode22
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node22_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=7776e73bd6104c7022fe2ac744d07ed2a3801989@ttAnode21:26656,22d04c99e7d3fbfb3709ea277f1b851cae9a5971@ttAnode23:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode22
  ttAnode23:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode23
    hostname: ttAnode23
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node23_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=8aae601028a4459c609a5d2352ca1cecccc2471a@ttAnode22:26656,0981841eec491856dcc3c2e3395b146b60a0ba7a@ttAnode24:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode23
  ttAnode24:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode24
    hostname: ttAnode24
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node24_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=22d04c99e7d3fbfb3709ea277f1b851cae9a5971@ttAnode23:26656,ea810ae5e94c4e71f031b223f8acaf41dfeb7eb0@ttAnode25:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode24
  ttAnode25:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode25
    hostname: ttAnode25
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node25_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=0981841eec491856dcc3c2e3395b146b60a0ba7a@ttAnode24:26656,1bf156704272373c360dcb8f1ea2d8fc5a252d25@ttAnode26:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode25
  ttAnode26:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode26
    hostname: ttAnode26
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node26_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=ea810ae5e94c4e71f031b223f8acaf41dfeb7eb0@ttAnode25:26656,715937e099450c4f73c4e945391b5973925ec725@ttAnode27:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode26
  ttAnode27:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode27
    hostname: ttAnode27
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node27_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=1bf156704272373c360dcb8f1ea2d8fc5a252d25@ttAnode26:26656,2752fe192004d243e5e523a490eb424f7b8aca7f@ttAnode28:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode27
  ttAnode28:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode28
    hostname: ttAnode28
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node28_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=715937e099450c4f73c4e945391b5973925ec725@ttAnode27:26656,82396b5f90baa308d4a834a4440e9fd4f34c9e6c@ttAnode29:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode28
  ttAnode29:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode29
    hostname: ttAnode29
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node29_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=2752fe192004d243e5e523a490eb424f7b8aca7f@ttAnode28:26656,816296870bf856a428e5c5738ae424e31f51f655@ttAnode30:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode29
  ttAnode3:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode3
    hostname: ttAnode3
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node3_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=a8819b91807edf54dced0448cc4697d4dccb9e84@ttAnode2:26656,3946bca2341f4b76b087f61a22bf1af1bd4223fc@ttAnode4:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode3
  ttAnode30:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode30
    hostname: ttAnode30
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node30_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=82396b5f90baa308d4a834a4440e9fd4f34c9e6c@ttAnode29:26656,b57c9157d18c9277a2a0ba05687923db66dd975e@ttAnode31:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode30
  ttAnode31:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode31
    hostname: ttAnode31
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node31_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=816296870bf856a428e5c5738ae424e31f51f655@ttAnode30:26656,221e93e5f65a21cea98f01ee640620dd09480963@ttAnode32:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode31
  ttAnode32:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode32
    hostname: ttAnode32
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node32_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=b57c9157d18c9277a2a0ba05687923db66dd975e@ttAnode31:26656,1feff0541e8fa3d305b3207de8d3af7f514793b4@ttAnode1:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode32
  ttAnode4:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode4
    hostname: ttAnode4
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node4_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=c4e06231035176586f934f07fa5c773fb512dc07@ttAnode3:26656,e25416125dec2f6d07534813241710b0607c6b9e@ttAnode5:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode4
  ttAnode5:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode5
    hostname: ttAnode5
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node5_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=3946bca2341f4b76b087f61a22bf1af1bd4223fc@ttAnode4:26656,3bdef7e804a45714164415d57930cc89a6417829@ttAnode6:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode5
  ttAnode6:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode6
    hostname: ttAnode6
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node6_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=e25416125dec2f6d07534813241710b0607c6b9e@ttAnode5:26656,2fa3fdf3346c8027e0a4444c2bae3170f641f190@ttAnode7:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode6
  ttAnode7:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode7
    hostname: ttAnode7
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node7_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=3bdef7e804a45714164415d57930cc89a6417829@ttAnode6:26656,949cd34c3ec080e43599daf478c862c0af3686c0@ttAnode8:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode7
  ttAnode8:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode8
    hostname: ttAnode8
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node8_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=2fa3fdf3346c8027e0a4444c2bae3170f641f190@ttAnode7:26656,ac947b8efa8b3feb9ac79ef4edd3975df06450a9@ttAnode9:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode8
  ttAnode9:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: ttAnode9
    hostname: ttAnode9
    tty: 'true'
    volumes:
    - /home/centos/network/node1/node9_data:/tendermint
    environment:
    - TASKID=A
    entrypoint:
    - sh
    - -c
    - 'tendermint node --p2p.persistent_peers=949cd34c3ec080e43599daf478c862c0af3686c0@ttAnode8:26656,bc85bfe8ed27c77143d2c62bace3762b3bc0f1a2@ttAnode10:26656
      --moniker=`hostname` --proxy_app=persistent_kvstore '
    networks:
      tendermintnet1:
        aliases:
        - ttAnode9
