version: 2
services:
  TTANode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode1
    hostname: TTANode1
    tty: true
    volumes: ['/home/centos/network/node1/node1_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=a84a8d3aa5a4034eb0e4a02564970edf9611b24d@TTANode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttAnode1]
  TTANode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTANode2
    hostname: TTANode2
    tty: true
    volumes: ['/home/centos/network/node1/node2_data:/tendermint']
    environment: [TASKID=A]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=0e75b3e26e42301a2646d03cc17bdf252fb21bd8@TTANode1:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttAnode2]
services:
  TTBNode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode1
    hostname: TTBNode1
    tty: true
    volumes: ['/home/centos/network/node2/node1_data:/tendermint']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=f7851405233e91827761b6eeac1ed70d83a8a787@TTBNode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttBnode1]
  TTBNode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTBNode2
    hostname: TTBNode2
    tty: true
    volumes: ['/home/centos/network/node2/node2_data:/tendermint']
    environment: [TASKID=B]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=911881956f38530bb9af59f72a4f50738636bf4d@TTBNode1:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttBnode2]
services:
  TTCNode1:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTCNode1
    hostname: TTCNode1
    tty: true
    volumes: ['/home/centos/network/node3/node1_data:/tendermint']
    environment: [TASKID=C]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=1d126216d727a596b9b2f5e45535d30d60dc4e03@TTCNode2:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttCnode1]
  TTCNode2:
    image: 10.77.70.142:5000/tendermint:v0.4
    container_name: TTCNode2
    hostname: TTCNode2
    tty: true
    volumes: ['/home/centos/network/node3/node2_data:/tendermint']
    environment: [TASKID=C]
    entrypoint: [sh, -c, 'tendermint node --p2p.persistent_peers=325a49403bee3e78fb4d681975b521e9c2ca9017@TTCNode1:26656
        --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false']
    networks:
      tendermintnet1:
        aliases: [ttCnode2]
  etcd1:
    container_name: etcd1
    image: 10.77.70.142:5000/etcd:v3.3.10
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    networks:
      tendermintnet1:
        aliases:
          - etcd1
    command: /usr/local/bin/etcd
      -name etcd1
      -advertise-client-urls http://etcd1:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd1:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      -initial-cluster-state new
    volumes:
      - "/usr/share/ca-certificates/:/etc/ssl/certs"
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=
      - project.owner=LHZ

  etcd2:
    container_name: etcd2
    image: 10.77.70.142:5000/etcd:v3.3.10
    ports:
      - "3379:2379"
      - "3380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    networks:
      tendermintnet1:
        aliases:
          - etcd2
    command: /usr/local/bin/etcd
      -name etcd2
      -advertise-client-urls http://etcd2:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd2:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      -initial-cluster-state new
    volumes:
      - "/usr/share/ca-certificates/:/etc/ssl/certs"
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=
      - project.owner=LHZ
  etcd3:
    container_name: etcd3
    image: 10.77.70.142:5000/etcd:v3.3.10
    ports:
      - "4379:2379"
      - "4380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    networks:
      tendermintnet1:
        aliases:
          - etcd3
    command: /usr/local/bin/etcd
      -name etcd3
      -advertise-client-urls http://etcd3:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd3:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      -initial-cluster-state new
    volumes:
      - "/usr/share/ca-certificates/:/etc/ssl/certs"
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=
      - project.owner=LHZ
  etcd4:
    container_name: etcd4
    image: 10.77.70.142:5000/etcd:v3.3.10
    ports:
      - "5379:2379"
      - "5380:2380"
    environment:
      - TZ=CST-8
      - LANG=zh_CN.UTF-8
    networks:
      tendermintnet1:
        aliases:
          - etcd4
    command: /usr/local/bin/etcd
      -name etcd4
      -advertise-client-urls http://etcd4:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd4:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token docker-etcd
      -initial-cluster etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      -initial-cluster-state new
    volumes:
      - "/usr/share/ca-certificates/:/etc/ssl/certs"
      # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=
      - project.owner=LHZ

networks:
  tendermintnet1:
    driver: host
